// resources/js/Components/Button.jsx
import { Link } from '@inertiajs/inertia-vue3'
import clsx from 'clsx'

const baseStyles = {
  solid:
    'group inline-flex items-center justify-center rounded-full py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2',
  outline:
    'group inline-flex ring-1 items-center justify-center rounded-full py-2 px-4 text-sm focus:outline-none',
}

const variantStyles = {
  solid: {
    slate:
      'bg-slate-900 text-white hover:bg-slate-700 hover:text-slate-100 active:bg-slate-800 active:text-slate-300 focus-visible:outline-slate-900',
    blue: 'bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600',
    white:
      'bg-white text-slate-900 hover:bg-blue-50 active:bg-blue-200 active:text-slate-600 focus-visible:outline-white',
  },
  outline: {
    slate:
      'ring-slate-200 text-slate-700 hover:text-slate-900 hover:ring-slate-300 active:bg-slate-100 active:text-slate-600 focus-visible:outline-blue-600 focus-visible:ring-slate-300',
    white:
      'ring-slate-700 text-white hover:ring-slate-500 active:ring-slate-700 active:text-slate-400 focus-visible:outline-white',
  },
}

export function Button({
  variant = 'solid',
  color = 'slate',
  className,
  ...props
}, {slots}) {
  return (
    <button
      className={clsx(
        baseStyles[variant],
        variantStyles[variant][color],
        className
      )}
      {...props}
    >{slots.default()}</button>
  )
}

export function ButtonLink({
  variant = 'solid',
  color = 'slate',
  href,
  className,
  ...props
}, {slots}) {
  return (
    <Link href={href} className={clsx(
          baseStyles[variant],
          variantStyles[variant][color],
          className
        )}
        {...props}>
      {slots.default()}
    </Link>
  )
}

// resources/js/Jetstream/Button.vue
<script setup>
defineProps({
    type: {
        type: String,
        default: 'submit',
    },
    isDark: {
        type: Boolean,
        default: true
    }
});
</script>

<template>
    <button :type="type" 
    :class="[
        'inline-flex items-center px-4 py-2  border border-transparent rounded-md font-semibold text-xs  uppercase tracking-widest   focus:outline-none  focus:ring  disabled:opacity-25 transition',
        isDark  ? 'bg-gray-800 text-white hover:bg-gray-700 active:bg-gray-900 focus:border-gray-900 focus:ring-gray-300' : 'bg-gray-100 text-gray-800 hover:bg-gray-50 active:bg-gray-100 focus:border-gray-100 focus:ring-gray-50',
    ]">
        <slot />
    </button>
</template>
